"""initial migration

Revision ID: d59f1c1a325d
Revises: 
Create Date: 2023-04-16 11:25:41.907924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59f1c1a325d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customerName', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('spoc', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('gst', sa.Text(), nullable=True),
    sa.Column('tenetid', sa.Text(), nullable=True),
    sa.Column('cloudUserName', sa.Text(), nullable=True),
    sa.Column('cloudPassword', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('customerid'),
    sa.UniqueConstraint('customerid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
